fixtures:

  repositories:
    "apt": "http://github.com/puppetlabs/puppetlabs-apt"
    "epel": "http://github.com/stahnma/puppet-module-epel"
    "gcc": "http://github.com/puppetlabs/puppetlabs-gcc"
    "php": "http://github.com/pahoughton/puppet-php"
    "policykit": "http://github.com/pahoughton/puppet-policykit"
    "python": "http://github.com/pahoughton/puppet-python"
    "stdlib": "http://github.com/puppetlabs/puppetlabs-stdlib"
    "vcsrepo": "http://github.com/puppetlabs/puppetlabs-vcsrepo"
    "sudo": "http://github.com/saz/puppet-sudo"
    "rpmfusion": "http://github.com/pahoughton/puppet-rpmfusion"
    #    "nginx": "http://github.com/pahoughton/puppet-nginx"
    
  symlinks:
    master: "#{source_dir}"
