name 'puppet-master'
version '0.0.1'
source 'git://cworld/puppet-master'
author 'Paul Houghton <paul4hough@gmail.com>'
description 'support classes'
summary 'users, services ...'
license 'ASL 2.0'
project_page 'https://github.com/pahoughton/puppet-master'

# FIXME dependency 'puppetlabs/policykit', '>=0.0.1'
dependency 'puppetlabs/vcsrepo', '>= 0.0.0'
dependency 'puppetlabs/java', '>= 0.0.0'
