#!/bin/bash
# pagent - 2014-02-15 07:29
#
# Copyright (c) 2014 Paul Houghton <paul_houghton@cable.comcast.com>
#
outfn="puppet.`/bin/date +%F-%H:%M:%S`.out"
time puppet agent --test > ~/$outfn 2>&1
if grep Error ~/outfn ; then
  echo "* * ERRORS * *"
else
  fold -w 78 -s ~/$outfn
fi
